name: Print The Text File

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev

jobs:
  print_text_file:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print the text file
        run: |
          echo "Printing the contents of the text file:"
          cat hello.txt
